services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: jobber
    ports:
      - '5432:5432'

  pulsar:
    image: apachepulsar/pulsar
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - 6650:6650
